version: '3'

services:
  mq:
    image: icr.io/ibm-messaging/mq:latest
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=passw0rd
      - MQ_ADMIN_PASSWORD=passw0rd
    volumes:
      - ./mqdata:/mnt/mqm